Refactor C++ code and prepare python integration
dendisuhubdy/quantum_compiler_optim pull request #1
Opened 2018-03-26 17:44 UTC by dendisuhubdy

- [x] adding include folder structure
- [x] adjusting graphs functions in different classes
- [x] adding RL base class

2018-03-26 18:04 UTC, dmitriy-serdyuk commented on src/main.cpp
> +#include "stdafx.h"
do you need to include `graphs.h`?

2018-03-26 18:14 UTC, dendisuhubdy commented on src/main.cpp
> +#include "stdafx.h"
Exactly sorry I forgot @dmitriy-serdyuk

2018-03-26 18:19 UTC, dendisuhubdy commented on src/main.cpp
> +#include "stdafx.h"
Adjusted in the following commit

2018-03-26 19:42 UTC, dmitriy-serdyuk commented
Dendi, I propose to split this PR into three:
  - Refactor C++ code and prepare to python integration
  - Create C++ - python interface
  - Add RL stuff

2018-03-26 19:50 UTC, dendisuhubdy commented
@dmitriy-serdyuk ok then, if you can review this. We can probably merge it then submit the C++ python interface up.

2018-03-26 20:01 UTC, dmitriy-serdyuk requested changes
We need to split mapping and optimization. As far as I understand, mapping starts at https://github.com/dendisuhubdy/quantum_compiler_optim/pull/1/files#diff-7ec3c68a81efff79b6ca22ac1f1eabbaR373

2018-03-26 20:01 UTC, dmitriy-serdyuk commented on src/main.cpp
>  void read_qasm(std::ifstream& infile) {
You are using namespace std already, do you need to reference it? I am not sure what C++ style guides say about this.

2018-03-26 20:05 UTC, dendisuhubdy commented on src/main.cpp
>  void read_qasm(std::ifstream& infile) {
I don't you're correct, in fact the good practice is not to use `using namespace std`, because it can cause conflicts.

2018-03-26 21:51 UTC, dmitriy-serdyuk commented on src/main.cpp
>  void read_qasm(std::ifstream& infile) {
👍

2018-03-27 17:35 UTC, dendisuhubdy commented
@dmitriy-serdyuk adjusted the source code to split between mapping and optimization.

2021-10-01 13:00 UTC, closed without merging